global_zones:
  paulon.org:
    masters:
      - 163.172.172.173
      - "2001:bc8:47a8:559::1"
    slaves:
      - 51.15.204.106
      - "2001:bc8:47ac:2017::1"
      - 163.172.14.205
      - "2001:bc8:2c9b::"
      - 51.15.199.212
    acme: "{{ vault_zones['paulon.org'].acme }}"
    soa: ns0.paulon.org.
    dnssec: yes
    mail: root+dns.paulon.org
  iiv.re:
    masters:
      - 163.172.172.173
      - "2001:bc8:47a8:559::1"
    slaves:
      - 51.15.204.106
      - "2001:bc8:47ac:2017::1"
      - 163.172.14.205
      - "2001:bc8:2c9b::"
      - 51.15.199.212
    soa: ns0.paulon.org.
    dnssec: yes
    mail: root+dns.paulon.org
  kelvinator.fr:
    masters:
      - 163.172.172.173
      - "2001:bc8:47a8:559::1"
    slaves:
      - 51.15.204.106
      - "2001:bc8:47ac:2017::1"
    acme: "{{ vault_zones['kelvinator.fr'].acme }}"
    soa: ns0.paulon.org.
    dnssec: yes
    mail: root+dns.paulon.org
  servens.org:
    masters: 
      - 185.230.76.3
    slaves: []
  maximebombar.fr:
    masters:
      - 51.15.204.106
      - "2001:bc8:47ac:2017::1"
    slaves: []
  satellist.fr:
    masters:
      - 51.15.204.106
      - "2001:bc8:47ac:2017::1"
    slaves: []