---
- name: "Install bind9"
  apt:
    update_cache: True
    name:
      - bind9
    state: present
  register: apt_result
  retries: 3
  until: apt_result is succeeded

- name: Deploy config
  template:
    src: '{{ item }}.j2'
    dest: '/{{ item }}'
    owner: root
    group: bind
  loop:
    - etc/bind/named.conf.local
    - etc/bind/named.conf.options
  notify: Restart bind

- name: deploy zones
  template:
    src: "var/cache/bind/db.{{ item }}.j2"
    dest: "/var/cache/bind/db.{{ item }}"
    owner: root
    group: bind
  when:
    - (zones[item].master)
  loop: "{{ zones.keys() }}"
  notify: Restart bind

- name: deploy acme zones
  template:
    src: "var/cache/bind/db.acme.j2"
    dest: "/var/cache/bind/db._acme-challenge.{{ item }}"
    owner: root
    group: bind
  when:
    - (zones[item].master and global_zones[item].get("acme"))
  loop: "{{ zones.keys() }}"
  notify: Restart bind
